name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: gcc /tools/cvm/src/cvm.c
