name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./tools/cvm/src/

    steps:
    - name: Build
      shell: bash
      run: gcc cvm.c -o cvm
      working-directory: ${{evn.working-directory}}
