name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./tools

    steps:
    - name: Build
      shell: bash
      run: gcc cvm/src/cvm.c
