name: C/C++ CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Build
      shell: bash
      run: chmod +x "${GITHUB_WORKSPACE}/tools/cvm/src/cvm.c"
