
name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install libglu1-mesa-dev
      run: sudo apt-get install libglu1-mesa-dev
    - name: install GLFW
      run: sudo apt-get install libglfw3
    - name: install GLFW-dev
      run: sudo apt-get install libglfw3-dev
    - name: build
      run: gcc tools/cvm/src/cvm.c -lglfw -lGLU -lGL
