name: C/C++ CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Build
      shell: bash
      run: cd ..
    - name: Build2
      shell: bash
      run: cd ..
    - name: Build3
      shell: bash
      run: cd tools
